site: JLC - BETA-01
title: JLC - Portfolio 
greetings: JLC - Portfolio
description: >-
  
  Commercial Art and collabrations by J.L. Christian
  Christian specializes in branding, campaigns, and custom designs that bring ideas to life. With a focus on impactful visuals and innovative solutions, each project is tailored to tell a story.
 


lang: en-US
timezone:  United States/California
repo: https://jlchristian.com # site repo [optional]
data-theme: "light" # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: J.L. Christian - Portfolio
  bio: J.L. Christian is an innovative and visionary commercial art director whose work seamlessly blends fine art sensibilities with compelling visual storytelling. With a keen eye for detail and a passion for creating evocative narratives, Christian specializes in crafting campaigns that resonate deeply with audiences. His expertise spans branding, advertising, and multimedia, showcasing a mastery of design that elevates products and experiences into works of art.
    Christian’s distinctive approach stems from his background as a fine artist, where themes of cultural heritage, history, and esoteric symbolism have informed his aesthetic direction. As a commercial art director, he bridges these artistic foundations with strategic thinking, delivering polished, impactful visuals that captivate and inspire. Whether developing high-end marketing concepts or overseeing creative teams, J.L. Christian consistently redefines the intersection of art and commerce.
  userpicture: 
  username: # general username
  github: SeimiNomore # github username
   # twitter username
   # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: mr.jonathanchristian@gmail.com # email adress

# Font Settings
googlewebfonts: -apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"

# URL settings
url: "https://jlchristian.com" # Domain Name of host. [username].github.io for github pages
baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 

markdown:
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

