site: JLC - Portfolio
title: Portfolio 
greetings: 
description: >-
 <h5>J.L. Christian - Portfolio</h5> 
 Explore a curated showcase of artistic mastery, offering:  
 <b>Commercial Art by J.L. Christian</b>
 Where creativity meets strategy— J.L. Christian specializes in branding, campaigns, and custom designs that bring ideas to life. With a focus on impactful visuals and innovative solutions, each project is tailored to tell a story.
 


lang: en-US
timezone:  United States/California
repo: https://jlchristian.com # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: J.L. Christian - Portfolio
  bio: just a minimalist, personal blog
  userpicture: 
  username: # general username
  github: SeimiNomore # github username
   # twitter username
   # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: mr.jonathanchristian@gmail.com # email adress

# Font Settings
googlewebfonts: -apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"

# URL settings
url: "https://jlchristian.com" # Domain Name of host. [username].github.io for github pages
baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown:
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


