site: JLC - Portfolio
title: Portfolio 
greetings: 
description: >-
 <h3>J.L. Christian - Portfolio</h3> 
 Welcome to the online portfolio of J.L. Christian. This portfolio includes: - Processes: Insight into the creative process, from conceptualization to completion. - Digital Art: A diverse array of visually striking digital artworks. - Art Direction: Case studies and projects showcasing cohesive results. - Collaborations: Highlights of partnerships and unique works.
lang: en-US
timezone:  United States/California
repo: https://jlchristian.com # site repo [optional]
data-theme: light # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: J.L. Christian - Portfolio
  bio: just a minimalist, personal blog
  userpicture: 
  username: # general username
  github: SeimiNomore # github username
   # twitter username
   # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: your-email@email.com # email adress

# Font Settings
googlewebfonts: -apple-system,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji";

# URL settings
url: "https://jlchristian.com" # Domain Name of host. [username].github.io for github pages
baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown:
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


